In [18]:
# Import necessary libraries
import numpy as np
import pandas as pd

In [19]:
# Set seed for reproducibility
np.random.seed(0)

In [22]:
# Generate an array of random numbers
data = np.random.randint(1, 501, size=(10,50))
data

array([[243, 359,  21, 172, 119, 129, 485, 366, 106, 195, 226, 141, 272,
        119,  34, 152, 397, 390,  39, 258, 267,   7, 382, 263, 103, 423,
        332, 371, 342, 383, 371, 179, 308, 259, 333, 158,  10, 116, 457,
        390, 117, 182, 236, 194, 300,  80,  63, 333,  48,  77],
       [150, 121, 275, 346,  14, 223,  93, 237, 106, 214,   7, 101,  49,
         41, 411, 159, 390, 144, 448, 486,  38,  60, 114,  96, 353, 497,
        209, 289,  63, 395, 397,  94, 321, 414, 347, 488, 151, 404, 390,
        293,  84, 128, 485, 262, 349, 461, 155, 242,  84, 397],
       [487, 136, 181,  81, 414,   1, 216, 208, 331, 253, 132,  62, 324,
        145, 369, 458,  85, 117, 230, 256, 313, 319, 441,  49, 146, 374,
        442,  10, 493, 191,  80, 231, 207, 418, 389, 401, 229, 328, 319,
        280, 348, 367,   8, 279, 355, 159, 247,  81, 156,  48],
       [496, 115,  12, 472, 335, 488, 287,  91, 291,  55, 338, 164,  72,
        366, 316, 113, 422,  69, 438,  14, 102, 276, 364, 265, 353, 210,
     

In [23]:
# Calculate the sum of each row
row_sums = data.sum(axis=1)
row_sums

array([11307, 12075, 12194, 12408, 12760, 12143, 13107, 12674, 13541,
       12325])

In [24]:
# Calculate the sum of each column
column_sums = data.sum(axis=0)
column_sums

array([2762, 2701, 1705, 3155, 2381, 2250, 2578, 2580, 1868, 2573, 2038,
       1758, 2345, 1943, 2322, 2574, 3013, 2236, 3334, 2830, 2337, 1897,
       2858, 2129, 2411, 2855, 2993, 2686, 2089, 3284, 2648, 2169, 2167,
       2900, 3329, 2999, 2003, 2062, 3120, 2304, 2327, 2125, 2578, 2734,
       3343, 2270, 2423, 2864, 2190, 1494])

In [25]:
# Calculate the sum of all entries
data_sum = data.sum()
data_sum

124534

In [26]:
# Generate descriptive statistics for the array
print('Minimum: ', data.min())
print('Maximum: ', data.max())
print('Average: ', data.mean())
print('Standard Deviation: ', data.std())

Minimum:  1
Maximum:  497
Average:  249.068
Standard Deviation:  138.69599625079306


In [27]:
# To sort using pandas, I have to turn the array into a dataframe
df = pd.DataFrame(data)
df.head()

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0  243  359   21  172  119  129  485  366  106  195  ...  117  182  236  194   
1  150  121  275  346   14  223   93  237  106  214  ...   84  128  485  262   
2  487  136  181   81  414    1  216  208  331  253  ...  348  367    8  279   
3  496  115   12  472  335  488  287   91  291   55  ...  261  149  363   75   
4   94  170   41  189  210  180  297   60  491  479  ...   44  111  454  375   

    44   45   46   47   48   49  
0  300   80   63  333   48   77  
1  349  461  155  242   84  397  
2  355  159  247   81  156   48  
3  124  452  215  317  230  251  
4  404  240  279  366  396   12  

[5 rows x 50 columns]

In [28]:
# Sort the dataframe on row 2
row_sort = df.sort_values(by=2, axis=1)
row_sort.head()

5    42   27   49   23   11   30   47   3    16  ...   25   34   35   4   \
0  129  236  371   77  263  141  371  333  172  397  ...  423  333  158  119   
1  223  485  289  397   96  101  397  242  346  390  ...  497  347  488   14   
2    1    8   10   48   49   62   80   81   81   85  ...  374  389  401  414   
3  488  363  381  251  265  164  254  317  472  422  ...  210  231  425  335   
4  180  454  368   12  201  226  218  366  189  217  ...   88  464  102  210   

    33   22   26   15   0    28  
0  259  382  332  152  243  342  
1  414  114  209  159  150   63  
2  418  441  442  458  487  493  
3  465  364  198  113  496  101  
4  217  280  294  383   94  448  

[5 rows x 50 columns]

In [30]:
# Sort the dataframe on column 2
column_sort = df.sort_values(by=2)
column_sort.head()

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
3  496  115   12  472  335  488  287   91  291   55  ...  261  149  363   75   
0  243  359   21  172  119  129  485  366  106  195  ...  117  182  236  194   
4   94  170   41  189  210  180  297   60  491  479  ...   44  111  454  375   
5  418  392  120  283   49  200  240  183   97  357  ...  388   78  268  398   
6   22  405  171  379  442  146  102  474  245  470  ...  414  259  134  378   

    44   45   46   47   48   49  
3  124  452  215  317  230  251  
0  300   80   63  333   48   77  
4  404  240  279  366  396   12  
5  485   82  155  455  176   99  
6  456  272  335  420  181  360  

[5 rows x 50 columns]